FROM oven/bun:1.3-alpine

ENV BUN_INSTALL_CACHE_DIR=/bun_cache

RUN mkdir /bun_cache && \
    mkdir /home/bun/app/node_modules && \
    mkdir /home/bun/app/packages/frontend/node_modules -p && \
    mkdir /home/bun/app/packages/backend/node_modules -p && \
    chown -R bun:bun /home/bun/app && \
    chown -R bun:bun /bun_cache

USER bun

WORKDIR /home/bun/app

COPY ./package.json /home/bun/app
COPY ./packages/frontend/package.json /home/bun/app/packages/frontend
COPY ./packages/backend/package.json /home/bun/app/packages/backend

RUN bun i