name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ghcr.io/${{ github.repository }}/todo-react-elysia-backend:${{ github.sha }},ghcr.io/${{ github.repository }}/todo-react-elysia-backend:unstable
          labels: |
            org.opencontainers.image.source=https://github.com/shaileshaanand/todo-react-elysia
            org.opencontainers.image.title=todo-react-elysia-backend
            org.opencontainers.image.description=Backend image for todo-react-elysia

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/todo-react-elysia-frontend:${{ github.sha }},ghcr.io/${{ github.repository }}/todo-react-elysia-frontend:unstable
          labels: |
            org.opencontainers.image.source=https://github.com/shaileshaanand/todo-react-elysia
            org.opencontainers.image.title=todo-react-elysia-frontend
            org.opencontainers.image.description=Frontend image for todo-react-elysia
